baseURL = "https://amplify-ios-workshop.go-aws.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Amplify iOS Workshop"
theme = "hugo-theme-learn"
uglyurls = true
googleAnalytics = "UA-151590472-1"
sectionPagesMenu = "main"
pygmentsCodeFences = true

[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Sébastien Stormacq"
description = "Amplify iOS Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle = true
disableInlineCopyToClipBoard = true

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @sebsto"
identifier = "tw"
url = "https://twitter.com/intent/user?screen_name=sebsto"
weight = 1

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]
